import { Router } from "express";
import authRouter from "./routers/auth.routes";
import connectEmailRouter from "./routers/connect-email.routes";
import webhookRouter from "./routers/webhook.routes";
import mailRouter from "./routers/mail.routes";
import analyticsRouter from "./routers/analytics.routes";
import templateRouter from "./routers/template.routes";
import aiRouter from "./routers/ai.routes";
import conversationRouter from "./routers/conversation.routes";
import realtimeRouter from "./routers/realtime.routes";
import integrationRouter from "./routers/integrations.routes";

const router = Router();
router.use("/auth", authRouter);
router.use("/connect", connectEmailRouter);
router.use("/webhook", webhookRouter);
router.use("/mail", mailRouter);
router.use("/analytics", analyticsRouter);
router.use("/templates", templateRouter);
router.use("/ai", aiRouter);
router.use("/conversations", conversationRouter);
router.use("/integrations", integrationRouter);
router.use("/realtime", realtimeRouter);
export default router;
